### ISSUE TITLE
계층형 아키텍쳐 적용 && 리팩토링

### ISSUE THREAD

**Issue by 5minho** [squad-b/work-assistant-api#52]
서로 관심사가 비슷한 것끼리 한 계층을 묶어 유지보수하기 쉬운 어플리케이션을 만든다.

표현 계층 - 응용 계층 - 도메인 계층 - 인프라스터럭처 계층 으로 나눈다.

계층마다 각 계층의 역할과 책임을 잘 키지고 있는지 검토 후 그렇지 않으면 리팩토링 한다.

**Comment by 5minho** [comment]
**presentation layer**
* 클라이언트로 부터 request 를 받고 response 를 응답하는 api 정의

**application layer**
* 어플리케이션의 기능 정의
* 트랜잭션 관리

**domain layer**
* 비즈니스 로직 정의
* 다른 layer 에 의존하지 않아야 하고, 개발자가 가장 신경을 많이 써야 한다.
* 테스트 코드 필수

**Comment by ydh6226** [comment]
infrastructure 에 있는 클래스와 하위 패키지인 config 있는 클래스를 어떤 기준으로 나누신건가요??

<img width="396" alt="스크린샷 2021-08-21 오후 9 48 34" src="https://user-images.githubusercontent.com/53700256/130322304-d6bf0f99-337f-4a77-ba34-815b29b3d77e.png">

**Comment by 5minho** [comment]
config 아래에 스프링 기술에 의존하는 클래스들을 두었습니다.
그러고 보니 config 는 좀 헷갈리고 패키지 명을 config 가 아닌, boot, spring 으로 지어도 될거 같네요?
@ydh6226

**Comment by ydh6226** [comment]
패키지명을 바꾸는것도 좋을 것 같네요
감사합니다!
